on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  bocusa-balance:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl 'https://ebanking.bocusa.com/newpbank/gw/acct/bal' \
            -H 'Accept: application/json, text/plain, */*' \
            -H 'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
            -H 'Connection: keep-alive' \
            -H 'Content-Type: application/json;charset=UTF-8' \
            -H 'Origin: https://ebanking.bocusa.com' \
            -H 'Referer: https://ebanking.bocusa.com/ibank/account/activity' \
            -H 'Sec-Fetch-Dest: empty' \
            -H 'Sec-Fetch-Mode: cors' \
            -H 'Sec-Fetch-Site: same-origin' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
            -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            --data-raw "{\"accountNo\":\"${{ secrets.BOCUSA_ACCOUNT_NO }}\"}" \
            --cookie "${{ secrets.BOCUSA_COOKIE }}" -c cookie.txt \
            | jq '._data.respData.BOOK_BAL'
